// 根项目配置（不含 application 配置）
// CI 会自动生成 gradle wrapper，所以无需其他额外配置

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
