name: Check Keystore

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Decode keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > signing.keystore

      - name: Check keystore content
        run: |
          keytool -list -v -keystore signing.keystore -storepass "${{ secrets.KEY_STORE_PASSWORD }}"
